### ISSUE TITLE
The Akinator translation to german doesn' work

### ISSUE THREAD

**Issue by Schokolino1** [NinjaSnail1080/akinator.py#3] opened 2019-06-11 13:57 UTC
Hello
I have a problem with the Akinator for Python. It works very well  but when  I change the language to geman and I start the script, the program hangs.  But when I change it to france or italy it works. I hope you can help me to have  the german language to work .
Thanks

**Comment by Schokolino1** [comment] 2019-06-11 16:56
and i found out that every language that is in the utils.py Document with the srv7 don't work.
i don't no why

**Comment by NinjaSnail1080** [comment] 2019-06-28 12:24
I'm sorry it took so long for me to respond. For some reason, I didn't get the notification when you opened the issue.

I tested all the languages, and my findings are the same as yours, with the addition of `fr2` also not working. However, I didn't come up with the list of servers. I got them from another repository here: https://github.com/jgoralcz/aki-api. So I don't know why these languages aren't working. I'll open a new issue on that repo and see if I can find out why.

**Comment by Schokolino1** [comment] 2019-06-28 12:30
Ok thank you

**Comment by NinjaSnail1080** [comment] 2019-07-15 17:56
The problem is fixed now. The servers that started with `srv7` and the `fr2` have been changed and those languages are working again. However, the Russian server suddenly stopped working and I haven't been able to get it to work, but that's a problem for another day.

**Closed by NinjaSnail1080** 2019-07-15 17:56 UTC
Labels: help wanted

**Comment by Schokolino1** [comment] 2019-07-15 20:10
Thanks
