### ISSUE TITLE
Akinator fails to start

### ISSUE THREAD

**Issue by srevinsaju** [NinjaSnail1080/akinator.py#9] opened 2020-04-25 12:59 UTC
On `aki.start_game("en")` or `aki.start_game("en2")` or `aki.start_game("en3")`, the akinator fails to start. This might be due to the change in servers again. It keeps going into a loop, 

On KeyboardInterrupt, this happens 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ss/.local/lib/python3.8/site-packages/akinator/akinator.py", line 127, in start_game
    r = requests.get(NEW_SESSION_URL.format(self.server, self.timestamp, self.uid, self.frontaddr))
  File "/home/ss/.local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
KeyboardInterrupt

```

Please feel free to request more information, if the information provided is not enough.
Thanks

**Comment by TollyThaWally** [comment] 2020-04-28 20:28
Can you elaborate on "fails to start"? What happens if you just leave it without interrupting? This is most likely a duplicate of #8 as that can take up to 2 minutes of waiting for the error to show. On another note, the server changing isn't the issue, I've changed the server to what the official page is currently using and #8 still occurs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by srevinsaju** [comment] 2020-04-29 15:20
I have not kept pinging the server. I will try it today nd let you know. Thanks

**Comment by srevinsaju** [comment] 2020-04-29 16:37
This is the traceback I received
```python
>>> a = akinator.Akinator()
>>> dir(a)
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_get_session_info', '_parse_response', '_update', 'answer', 'back', 'description', 'frontaddr', 'name', 'picture', 'progression', 'question', 'server', 'session', 'signature', 'start_game', 'step', 'timestamp', 'uid', 'win']
>>> a.start_game()
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in conn
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object d out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ss/.local/lib/python3.8/site-packages/requests/adapters.py", line 43
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in 
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in incr
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='srv14.akinator.com', p861332693_1588173715.1495183&partner=1&player=website-desktop&uid_ext_session=27433C%25%253E%25%2527AV%25%2527&constraint=ETAT%3C%3E'AV' (Caused by NewConnectionErrh a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ss/.local/lib/python3.8/site-packages/akinator/akinator.py", line 12
    r = requests.get(NEW_SESSION_URL.format(self.server, self.timestamp, self.uid,
  File "/home/ss/.local/lib/python3.8/site-packages/requests/api.py", line 76, in 
    return request('get', url, params=params, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/api.py", line 61, in 
    return session.request(method=method, url=url, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/sessions.py", line 53
    resp = self.send(prep, **send_kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/sessions.py", line 64
    r = adapter.send(request, **kwargs)
  File "/home/ss/.local/lib/python3.8/site-packages/requests/adapters.py", line 51
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='srv14.akinator.com'254861332693_1588173715.1495183&partner=1&player=website-desktop&uid_ext_session=2%253C%25%253E%25%2527AV%25%2527&constraint=ETAT%3C%3E'AV' (Caused by NewConnectionlish a new connection: [Errno 110] Connection timed out'))
```

**Comment by adamharsh** [comment] 2020-05-01 04:47
I am also getting this error. It was working fine earlier

**Comment by adrianlubitz** [comment] 2020-07-07 08:31
Seems like the servers are still not reachable. 
NPM package uses other websocket addresses.

see. https://github.com/jgoralcz/aki-api/blob/develop/src/lib/functions/GetURL.js

I was trying to replace one of the ones you used in this implementation put that was giving me the following error:

```
trying: https://srv13.akinator.com:9361/ws/new_session?callback=jQuery331005089254861332693_1594109091.3251321&partner=1&player=website-desktop&uid_ext_session=88d7d0f4-c028-11ea-9eb9-0cc47a691511&frontaddr=MTQ3LjEzNS4xMjkuOTM=&constraint=ETAT%%3C%%3E%%27AV%%27&constraint=ETAT<>'AV'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adrianlubitz/opt/anaconda3/envs/pyHook/lib/python3.7/site-packages/akinator/akinator.py", line 135, in start_game
    return raise_connection_error(resp["completion"])
  File "/Users/adrianlubitz/opt/anaconda3/envs/pyHook/lib/python3.7/site-packages/akinator/utils.py", line 132, in raise_connection_error
    raise AkiConnectionFailure("An unknown error has occured. Server response: {}".format(response))
akinator.exceptions.AkiConnectionFailure: An unknown error has occured. Server response: KO - BAD REQUEST 1
>>> 
```
The first line is a debugprint I added to see if which server was taken.

Is there an official source for these websocket addresses? Couldn't find anything. 

Besides the fact that it is not working right now the lib looks really pretty and I would love to use it. Hope that can be fixed soon 👍

**Comment by NinjaSnail1080** [comment] 2020-07-07 19:29
The library has been updated. Sorry it took so long

**Comment by srevinsaju** [comment] 2020-07-07 19:30
Thanks a lot. Was eagerly waiting for an update :smile:

**Closed by NinjaSnail1080** 2020-07-07 19:29 UTC
